[package]
name = "FinSc-Multiset-Transform-Wiki"
version = "0.1.0"
ipkg = "FinSc-Multiset-Transform-Wiki.ipkg"

[custom.all.idris2-QuickCheck]
type = "local"
path = "../idris2-QuickCheck"
ipkg = "idris2-QuickCheck.ipkg"

[custom.all.FinSc-Multiset-Core]
type = "local"
path = "../FinSc-Multiset-Core"
ipkg = "FinSc-Multiset-Core.ipkg"

[custom.all.FinSc-Multiset-Transform]
type = "local"
path = "../FinSc-Multiset-Transform"
ipkg = "FinSc-Multiset-Transform.ipkg"

[custom.all.FinSc-Dihedron]
type = "local"
path = "../FinSc-Dihedron"
ipkg = "FinSc-Dihedron.ipkg"

[custom.all.FinSc-Cosmos]
type = "local"
path = "../FinSc-Cosmos"
ipkg = "FinSc-Cosmos.ipkg"
